<?php

namespace Database\Seeders;

use App\Models\Producto;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now(); // Obtener la fecha y hora actuales

        $productos = [
            [
                'nombre' => 'Café Caramel con Chocolate',
                'precio' => 59.9,
                'imagen' => 'cafe_01',
                'categoria_id' => 1,
                'id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Café Frio con Chocolate Grande',
                'precio' => 49.9,
                'imagen' => 'cafe_02',
                'categoria_id' => 1,
                'id' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Latte Frio con Chocolate Grande',
                'precio' => 54.9,
                'imagen' => 'cafe_03',
                'categoria_id' => 1,
                'id' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Latte Frio con Chocolate Grande',
                'precio' => 54.9,
                'imagen' => 'cafe_04',
                'categoria_id' => 1,
                'id' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Malteada Fria con Chocolate Grande',
                'precio' => 54.9,
                'imagen' => 'cafe_05',
                'categoria_id' => 1,
                'id' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Café Mocha Caliente Chico',
                'precio' => 39.9,
                'imagen' => 'cafe_06',
                'categoria_id' => 1,
                'id' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Café Mocha Caliente Grande con Chocolate',
                'precio' => 59.9,
                'imagen' => 'cafe_07',
                'categoria_id' => 1,
                'id' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Café Caliente Capuchino Grande',
                'precio' => 59.9,
                'imagen' => 'cafe_08',
                'categoria_id' => 1,
                'id' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Café Mocha Caliente Mediano',
                'precio' => 49.9,
                'imagen' => 'cafe_09',
                'categoria_id' => 1,
                'id' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Café Mocha Frio con Caramelo Mediano',
                'precio' => 49.9,
                'imagen' => 'cafe_10',
                'categoria_id' => 1,
                'id' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Café Mocha Frio con Chocolate Mediano',
                'precio' => 49.9,
                'imagen' => 'cafe_11',
                'categoria_id' => 1,
                'id' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Café Espresso',
                'precio' => 29.9,
                'imagen' => 'cafe_12',
                'categoria_id' => 1,
                'id' => 12,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Café Capuchino Grande con Caramelo',
                'precio' => 59.9,
                'imagen' => 'cafe_13',
                'categoria_id' => 1,
                'id' => 13,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Café Caramelo Grande',
                'precio' => 59.9,
                'imagen' => 'cafe_14',
                'categoria_id' => 1,
                'id' => 14,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Paquete de 3 donas de Chocolate',
                'precio' => 39.9,
                'imagen' => 'donas_01',
                'categoria_id' => 4,
                'id' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Paquete de 3 donas Glaseadas',
                'precio' => 39.9,
                'imagen' => 'donas_02',
                'categoria_id' => 4,
                'id' => 16,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Dona de Fresa',
                'precio' => 19.9,
                'imagen' => 'donas_03',
                'categoria_id' => 4,
                'id' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Dona con Galleta de Chocolate',
                'precio' => 19.9,
                'imagen' => 'donas_04',
                'categoria_id' => 4,
                'id' => 18,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Dona glass con Chispas Sabor Fresa',
                'precio' => 19.9,
                'imagen' => 'donas_05',
                'categoria_id' => 4,
                'id' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Dona glass con Chocolate',
                'precio' => 19.9,
                'imagen' => 'donas_06',
                'categoria_id' => 4,
                'id' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Dona de Chocolate con MÁS Chocolate',
                'precio' => 19.9,
                'imagen' => 'donas_07',
                'categoria_id' => 4,
                'id' => 21,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Paquete de 3 donas de Chocolate',
                'precio' => 39.9,
                'imagen' => 'donas_08',
                'categoria_id' => 4,
                'id' => 22,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Paquete de 3 donas con Vainilla y Chocolate',
                'precio' => 39.9,
                'imagen' => 'donas_09',
                'categoria_id' => 4,
                'id' => 23,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Paquete de 6 Donas',
                'precio' => 69.9,
                'imagen' => 'donas_10',
                'categoria_id' => 4,
                'id' => 24,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Paquete de 3 Variadas',
                'precio' => 39.9,
                'imagen' => 'donas_11',
                'categoria_id' => 4,
                'id' => 25,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Dona Natural con Chocolate',
                'precio' => 19.9,
                'imagen' => 'donas_12',
                'categoria_id' => 4,
                'id' => 26,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Paquete de 3 Donas de Chocolate con Chispas',
                'precio' => 39.9,
                'imagen' => 'donas_13',
                'categoria_id' => 4,
                'id' => 27,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Dona Chocolate y Coco',
                'precio' => 19.9,
                'imagen' => 'donas_14',
                'categoria_id' => 4,
                'id' => 28,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Paquete Galletas de Chocolate',
                'precio' => 29.9,
                'imagen' => 'galletas_01',
                'categoria_id' => 6,
                'id' => 29,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Paquete Galletas de Chocolate y Avena',
                'precio' => 39.9,
                'imagen' => 'galletas_02',
                'categoria_id' => 6,
                'id' => 30,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Paquete de Muffins de Vainilla',
                'precio' => 39.9,
                'imagen' => 'galletas_03',
                'categoria_id' => 6,
                'id' => 31,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Paquete de 4 Galletas de Avena',
                'precio' => 24.9,
                'imagen' => 'galletas_04',
                'categoria_id' => 6,
                'id' => 32,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Galletas de Mantequilla Variadas',
                'precio' => 39.9,
                'imagen' => 'galletas_05',
                'categoria_id' => 6,
                'id' => 33,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Galletas de sabores frutales',
                'precio' => 39.9,
                'imagen' => 'galletas_06',
                'categoria_id' => 6,
                'id' => 34,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Hamburguesa Sencilla',
                'precio' => 59.9,
                'imagen' => 'hamburguesas_01',
                'categoria_id' => 2,
                'id' => 35,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Hamburguesa de Pollo',
                'precio' => 59.9,
                'imagen' => 'hamburguesas_02',
                'categoria_id' => 2,
                'id' => 36,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Hamburguesa de Pollo y Chili',
                'precio' => 59.9,
                'imagen' => 'hamburguesas_03',
                'categoria_id' => 2,
                'id' => 37,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Hamburguesa Queso y Pepinos',
                'precio' => 59.9,
                'imagen' => 'hamburguesas_04',
                'categoria_id' => 2,
                'id' => 38,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Hamburguesa Cuarto de Libra',
                'precio' => 59.9,
                'imagen' => 'hamburguesas_05',
                'categoria_id' => 2,
                'id' => 39,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Hamburguesa Doble Queso',
                'precio' => 69.9,
                'imagen' => 'hamburguesas_06',
                'categoria_id' => 2,
                'id' => 40,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Hot Dog Especial',
                'precio' => 49.9,
                'imagen' => 'hamburguesas_07',
                'categoria_id' => 2,
                'id' => 41,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Paquete 2 Hot Dogs',
                'precio' => 69.9,
                'imagen' => 'hamburguesas_08',
                'categoria_id' => 2,
                'id' => 42,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => '4 Rebanadas de Pay de Queso',
                'precio' => 69.9,
                'imagen' => 'pastel_01',
                'categoria_id' => 5,
                'id' => 43,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Waffle Especial',
                'precio' => 49.9,
                'imagen' => 'pastel_02',
                'categoria_id' => 5,
                'id' => 44,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Croissants De la casa',
                'precio' => 39.9,
                'imagen' => 'pastel_03',
                'categoria_id' => 5,
                'id' => 45,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Pay de Queso',
                'precio' => 19.9,
                'imagen' => 'pastel_04',
                'categoria_id' => 5,
                'id' => 46,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Pastel de Chocolate',
                'precio' => 29.9,
                'imagen' => 'pastel_05',
                'categoria_id' => 5,
                'id' => 47,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Rebanada Pastel de Chocolate',
                'precio' => 29.9,
                'imagen' => 'pastel_06',
                'categoria_id' => 5,
                'id' => 48,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Pizza Spicy con Doble Queso',
                'precio' => 69.9,
                'imagen' => 'pizzas_01',
                'categoria_id' => 3,
                'id' => 49,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Pizza Jamón y Queso',
                'precio' => 69.9,
                'imagen' => 'pizzas_02',
                'categoria_id' => 3,
                'id' => 50,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Pizza Doble Queso',
                'precio' => 69.9,
                'imagen' => 'pizzas_03',
                'categoria_id' => 3,
                'id' => 51,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Pizza Especial de la Casa',
                'precio' => 69.9,
                'imagen' => 'pizzas_04',
                'categoria_id' => 3,
                'id' => 52,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Pizza Chorizo',
                'precio' => 69.9,
                'imagen' => 'pizzas_05',
                'categoria_id' => 3,
                'id' => 53,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nombre' => 'Pizza Hawaiana',
                'precio' => 69.9,
                'imagen' => 'pizzas_06',
                'categoria_id' => 3,
                'id' => 54,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        Producto::insert($productos);
    }
}
